#ifndef AKU_MODULES_ANDROID_CONFIG_H
#define AKU_MODULES_ANDROID_CONFIG_H

	#ifndef AKU_WITH_ANDROID
		#define AKU_WITH_ANDROID 1
	#endif

	#ifndef AKU_WITH_ANDROID_ADCOLONY
		#define AKU_WITH_ANDROID_ADCOLONY 0
	#endif

	#ifndef AKU_WITH_ANDROID_AMAZON_BILLING
		#define AKU_WITH_ANDROID_AMAZON_BILLING 0
	#endif

	#ifndef AKU_WITH_ANDROID_CHARTBOOST
		#define AKU_WITH_ANDROID_CHARTBOOST 0
	#endif

	#ifndef AKU_WITH_ANDROID_CRITTERCISM
		#define AKU_WITH_ANDROID_CRITTERCISM 0
	#endif

	#ifndef AKU_WITH_ANDROID_FACEBOOK
		#define AKU_WITH_ANDROID_FACEBOOK 0
	#endif

	#ifndef AKU_WITH_ANDROID_FLURRY
		#define AKU_WITH_ANDROID_FLURRY 0
	#endif
	
	#ifndef AKU_WITH_ANDROID_FORTUMO
		#define AKU_WITH_ANDROID_FORTUMO 0
	#endif
	
	#ifndef AKU_WITH_ANDROID_GOOGLE_BILLING
		#define AKU_WITH_ANDROID_GOOGLE_BILLING 0
	#endif
	
	#ifndef AKU_WITH_ANDROID_GOOGLE_PUSH
		#define AKU_WITH_ANDROID_GOOGLE_PUSH 0
	#endif

	#ifndef AKU_WITH_ANDROID_GOOGLE_PLAY_SERVICES
		#define AKU_WITH_ANDROID_GOOGLE_PLAY_SERVICES 0
	#endif
	
	#ifndef AKU_WITH_ANDROID_TAPJOY
		#define AKU_WITH_ANDROID_TAPJOY 0
	#endif
	
  #ifndef AKU_WITH_ANDROID_TWITTER
	  #define AKU_WITH_ANDROID_TWITTER 0
  #endif

  #ifndef AKU_WITH_ANDROID_VUNGLE
	  #define AKU_WITH_ANDROID_VUNGLE 0
  #endif

#endif