#ifndef AKU_MODULES_ANDROID_CONFIG_H
#define AKU_MODULES_ANDROID_CONFIG_H

	#ifndef AKU_WITH_ANDROID
		#define AKU_WITH_ANDROID 1
	#endif

	#ifndef AKU_WITH_ANDROID_ADCOLONY
		#define AKU_WITH_ANDROID_ADCOLONY 1
	#endif

	#ifndef AKU_WITH_ANDROID_BILLING
		#define AKU_WITH_ANDROID_BILLING 1
	#endif

	#ifndef AKU_WITH_ANDROID_CHARTBOOST
		#define AKU_WITH_ANDROID_CHARTBOOST 1
	#endif

	#ifndef AKU_WITH_ANDROID_CRITTERCISM
		#define AKU_WITH_ANDROID_CRITTERCISM 1
	#endif

	#ifndef AKU_WITH_ANDROID_FACEBOOK
		#define AKU_WITH_ANDROID_FACEBOOK 1
	#endif

	#ifndef AKU_WITH_ANDROID_FLURRY
		#define AKU_WITH_ANDROID_FLURRY 1
	#endif

	#ifndef AKU_WITH_ANDROID_NOTIFICATIONS
		#define AKU_WITH_ANDROID_NOTIFICATIONS 1
	#endif

	#ifndef AKU_WITH_ANDROID_TAPJOY
		#define AKU_WITH_ANDROID_TAPJOY 1
	#endif

	#ifndef AKU_WITH_ANDROID_TSTOREWALL
		#define AKU_WITH_ANDROID_TSTOREWALL 0
	#endif

	#ifndef AKU_WITH_ANDROID_TSTOREGAMECENTER
		#define AKU_WITH_ANDROID_TSTOREGAMECENTER 0
	#endif

	#ifndef AKU_WITH_ANDROID_PLAYSERVICES
		#define AKU_WITH_ANDROID_PLAYSERVICES 1
	#endif

	#ifndef AKU_WITH_ANDROID_VUNGLE
		#define AKU_WITH_ANDROID_VUNGLE 1
	#endif

#endif