#ifndef AKU_MODULES_IOS_CONFIG_H
#define AKU_MODULES_IOS_CONFIG_H

	#ifndef AKU_WITH_IOS
		#define AKU_WITH_IOS 1
	#endif

	#ifndef AKU_WITH_IOS_ADCOLONY
		#define AKU_WITH_IOS_ADCOLONY 0
	#endif

	#ifndef AKU_WITH_IOS_BILLING
		#define AKU_WITH_IOS_BILLING 1
	#endif

	#ifndef AKU_WITH_IOS_CHARTBOOST
		#define AKU_WITH_IOS_CHARTBOOST 0
	#endif

	#ifndef AKU_WITH_IOS_CRITTERCISM
		#define AKU_WITH_IOS_CRITTERCISM 0
	#endif

	#ifndef AKU_WITH_IOS_FACEBOOK
		#define AKU_WITH_IOS_FACEBOOK 0
	#endif

	#ifndef AKU_WITH_IOS_FLURRY
		#define AKU_WITH_IOS_FLURRY 0
	#endif

	#ifndef AKU_WITH_IOS_GAMECENTER
		#define AKU_WITH_IOS_GAMECENTER 0
	#endif

	#ifndef AKU_WITH_IOS_MIXPANEL
		#define AKU_WITH_IOS_MIXPANEL 0
	#endif

	#ifndef AKU_WITH_IOS_MOBILE_APP_TRACKER
		#define AKU_WITH_IOS_MOBILE_APP_TRACKER 0
	#endif

	#ifndef AKU_WITH_IOS_TAPJOY
		#define AKU_WITH_IOS_TAPJOY 0
	#endif

	#ifndef AKU_WITH_IOS_URBAN_AIRSHIP
		#define AKU_WITH_IOS_URBAN_AIRSHIP 0
	#endif

	#ifndef AKU_WITH_IOS_VUNGLE
		#define AKU_WITH_IOS_VUNGLE 0
	#endif

#endif