// Copyright (c) 2010-2017 Zipline Games, Inc. All Rights Reserved.
// http://getmoai.com

#ifndef	MOAIGFXPRESETENUM_H
#define	MOAIGFXPRESETENUM_H

enum MOAIShaderPresetEnum {
	DECK2D_SHADER,
	DECK2D_SNAPPING_SHADER,
	FONT_SHADER,
	FONT_SNAPPING_SHADER,
	FONT_EFFECTS_SHADER,
	LINE_SHADER,
	LINE_SHADER_3D,
	MESH_SHADER,
	TOTAL_SHADERS,
	
	UNKNOWN_SHADER = 0xffffffff,
};

enum MOAIVertexFormatPresetEnum {
	XYZC,
	XYZWC,
	XYZWUVC,
	XYZWNNNC,
	XYZWNNNUVC,
	TOTAL_FORMATS,
	
	UNKNOWN_FORMAT = 0xffffffff,
};

#endif
