name: Moai SDK
markdown: redcarpet
highlighter: pygments
future: true
baseurl: /moai-sdk

collections:
  docs:
    output: true

defaults:
  -
    scope:
      path: ""
      type: docs
    values:
      layout: doc
      order: 0
