Keyboard = {

    A               = 97,
    B               = 98,
    C               = 99,
    D               = 100,
    E               = 101,
    F               = 102,
    G               = 103,
    H               = 104,
    I               = 105,
    J               = 106,
    K               = 107,
    L               = 108,
    M               = 109,
    N               = 110,
    O               = 111,
    P               = 112,
    Q               = 113,
    R               = 114,
    S               = 115,
    T               = 116,
    U               = 117,
    V               = 118,
    W               = 119,
    X               = 120,
    Y               = 121,
    Z               = 122,

    NUMBER_0        = 48,
    NUMBER_1        = 49,
    NUMBER_2        = 50,
    NUMBER_3        = 51,
    NUMBER_4        = 52,
    NUMBER_5        = 53,
    NUMBER_6        = 54,
    NUMBER_7        = 55,
    NUMBER_8        = 56,
    NUMBER_9        = 57,

    -- Modifiers

    BACKSPACE       = 8,
    TAB             = 9,
    ENTER           = 13,
    SHIFT           = 16,
    CTRL            = 17,
    ALT             = 18,
    ESCAPE          = 27,
    SPACE           = 32,

    --
    SINGLE_QUOTE    = 39,
    COMMA           = 44,
    MINUS           = 45,
    PERIOD          = 46,
    FORWARD_SLASH   = 47,
    COLON           = 58,
    EQUAL           = 61,
    OPEN_BRACKET    = 91,
    BACK_SLASH      = 92,
    CLOSE_BRACKET   = 93,
    PRIME           = 96

}