-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:d08de0fc19689dd0b345cef705a1f3a7$
-- 

return {
	texture = 'tiles-hd.png',
	frames = {
			{
				name = "tls-tiles.png",
				spriteColorRect = { x = 0, y = 0, width = 594, height = 594 },
				uvRect = { u0 = 0, v0 = 0, u1 = 0.580078, v1 = 0.580078 },
				spriteSourceSize = { width = 594, height = 594 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

