// Copyright (c) 2010-2017 Zipline Games, Inc. All Rights Reserved.
// http://getmoai.com

#ifndef ZLGFXENUM_H
#define ZLGFXENUM_H

// hardware PVR support is based on device
#ifdef MOAI_OS_IPHONE
	#define ZGL_DEVCAPS_PVR_TEXTURE 1
#else
	#define ZGL_DEVCAPS_PVR_TEXTURE 0
#endif

#define ZGL_FIRST_FLAG 0x70000000

//================================================================//
// ZLGfxEnum
//================================================================//
struct ZLGfxEnum {

	enum _ {

		NONE 									= 0,

		BLEND_FACTOR_DST_ALPHA					= ZGL_FIRST_FLAG,
		BLEND_FACTOR_DST_COLOR,
		BLEND_FACTOR_ONE,
		BLEND_FACTOR_ONE_MINUS_DST_ALPHA,
		BLEND_FACTOR_ONE_MINUS_DST_COLOR,
		BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
		BLEND_FACTOR_ONE_MINUS_SRC_COLOR,
		BLEND_FACTOR_SRC_ALPHA,
		BLEND_FACTOR_SRC_ALPHA_SATURATE,
		BLEND_FACTOR_SRC_COLOR,
		BLEND_FACTOR_ZERO,

		BLEND_MODE_ADD,
		BLEND_MODE_MAX,
		BLEND_MODE_MIN,
		BLEND_MODE_REVERSE_SUBTRACT,
		BLEND_MODE_SUBTRACT,

		BUFFER_TARGET_ARRAY,
		BUFFER_TARGET_ELEMENT_ARRAY,

		BUFFER_USAGE_DYNAMIC_COPY,
		BUFFER_USAGE_DYNAMIC_DRAW,
		BUFFER_USAGE_DYNAMIC_READ,
		BUFFER_USAGE_STATIC_COPY,
		BUFFER_USAGE_STATIC_DRAW,
		BUFFER_USAGE_STATIC_READ,
		BUFFER_USAGE_STREAM_COPY,
		BUFFER_USAGE_STREAM_DRAW,
		BUFFER_USAGE_STREAM_READ,

		CAPS_MAX_TEXTURE_SIZE,
		CAPS_MAX_TEXTURE_UNITS,

		COMPOSE_MODULATE,

		CULL_ALL,
		CULL_BACK,
		CULL_FRONT,

		DEPTH_ALWAYS,
		DEPTH_EQUAL,
		DEPTH_LESS,
		DEPTH_LEQUAL,
		DEPTH_GEQUAL,
		DEPTH_GREATER,
		DEPTH_NEVER,
		DEPTH_NOTEQUAL,

		ERROR_INVALID_ENUM,
		ERROR_INVALID_OPERATION,
		ERROR_INVALID_VALUE,
		ERROR_NONE,
		ERROR_OUT_OF_MEMORY,
		ERROR_STACK_OVERFLOW,
		ERROR_STACK_UNDERFLOW,

		ERROR_UNKNOWN,

		FRAMEBUFFER_ATTACHMENT_COLOR,
		FRAMEBUFFER_ATTACHMENT_DEPTH,
		FRAMEBUFFER_ATTACHMENT_STENCIL,

		FRAMEBUFFER_STATUS_COMPLETE,

		FRAMEBUFFER_TARGET_DRAW,
		FRAMEBUFFER_TARGET_READ,
		FRAMEBUFFER_TARGET_DRAW_READ,

		MATRIX_COLOR,
		MATRIX_MODELVIEW,
		MATRIX_PROJECTION,
		MATRIX_TEXTURE,

		PIPELINE_BLEND,
		PIPELINE_COLOR_ARRAY,
		PIPELINE_CULL,
		PIPELINE_DEPTH,
		PIPELINE_NORMAL_ARRAY,
		PIPELINE_SCISSOR,
		PIPELINE_TEXTURE_2D,
		PIPELINE_TEXTURE_COORD_ARRAY,
		PIPELINE_VERTEX_ARRAY,

		COLOR_INDEX,
		STENCIL_INDEX,
		DEPTH_COMPONENT,

		PIXEL_FORMAT_ALPHA,
		PIXEL_FORMAT_LUMINANCE,
		PIXEL_FORMAT_LUMINANCE_ALPHA,
		PIXEL_FORMAT_RED,
		PIXEL_FORMAT_RG,
		PIXEL_FORMAT_RGB,
		PIXEL_FORMAT_RGB4,
		PIXEL_FORMAT_RGB5_A1,
		PIXEL_FORMAT_RGB565,
		PIXEL_FORMAT_RGB8,
		PIXEL_FORMAT_BGR,
		PIXEL_FORMAT_RGBA,
		PIXEL_FORMAT_RGBA4,
		PIXEL_FORMAT_RGBA8,
		PIXEL_FORMAT_BGRA,

		PIXEL_FORMAT_DEPTH_COMPONENT16,
		PIXEL_FORMAT_STENCIL_INDEX8,

		PIXEL_TYPE_BYTE,
		PIXEL_TYPE_COMPRESSED_RGB_PVRTC_2BPPV1_IMG,
		PIXEL_TYPE_COMPRESSED_RGB_PVRTC_4BPPV1_IMG,
		PIXEL_TYPE_COMPRESSED_RGBA_PVRTC_2BPPV1_IMG,
		PIXEL_TYPE_COMPRESSED_RGBA_PVRTC_4BPPV1_IMG,
		PIXEL_TYPE_FLOAT,
		PIXEL_TYPE_INT,
		PIXEL_TYPE_SHORT,
		PIXEL_TYPE_UNSIGNED_BYTE,
		PIXEL_TYPE_UNSIGNED_BYTE_2_3_3_REV,
		PIXEL_TYPE_UNSIGNED_BYTE_3_3_2,
		PIXEL_TYPE_UNSIGNED_INT,
		PIXEL_TYPE_UNSIGNED_INT_8_8_8_8,
		PIXEL_TYPE_UNSIGNED_INT_8_8_8_8_REV,
		PIXEL_TYPE_UNSIGNED_INT_2_10_10_10_REV,
		PIXEL_TYPE_UNSIGNED_INT_10_10_10_2,
		PIXEL_TYPE_UNSIGNED_SHORT,
		PIXEL_TYPE_UNSIGNED_SHORT_5_6_5,
		PIXEL_TYPE_UNSIGNED_SHORT_5_6_5_REV,
		PIXEL_TYPE_UNSIGNED_SHORT_4_4_4_4,
		PIXEL_TYPE_UNSIGNED_SHORT_4_4_4_4_REV,
		PIXEL_TYPE_UNSIGNED_SHORT_1_5_5_5_REV,
		PIXEL_TYPE_UNSIGNED_SHORT_5_5_5_1,

		PRIM_LINE_LOOP,
		PRIM_LINE_STRIP,
		PRIM_LINES,
		PRIM_POINTS,
		PRIM_TRIANGLE_FAN,
		PRIM_TRIANGLE_STRIP,
		PRIM_TRIANGLES,

		PROGRAM_INFO_ACTIVE_ATTRIBUTES,
		PROGRAM_INFO_ACTIVE_ATTRIBUTE_MAX_LENGTH,
		PROGRAM_INFO_ACTIVE_UNIFORMS,
		PROGRAM_INFO_ACTIVE_UNIFORM_MAX_LENGTH,
		PROGRAM_INFO_ATTACHED_SHADERS,
		PROGRAM_INFO_DELETE_STATUS,
		PROGRAM_INFO_LOG_LENGTH,
		PROGRAM_INFO_LINK_STATUS,
		PROGRAM_INFO_VALIDATE_STATUS,

		SAMPLE_LINEAR,
		SAMPLE_LINEAR_MIPMAP_LINEAR,
		SAMPLE_LINEAR_MIPMAP_NEAREST,
		SAMPLE_NEAREST,
		SAMPLE_NEAREST_MIPMAP_LINEAR,
		SAMPLE_NEAREST_MIPMAP_NEAREST,

		SHADER_INFO_COMPILE_STATUS,
		SHADER_INFO_DELETE_STATUS,
		SHADER_INFO_LOG_LENGTH,
		SHADER_INFO_SOURCE_LENGTH,
		SHADER_INFO_TYPE,

		SHADER_TYPE_TESS_CONTROL,
		SHADER_TYPE_TESS_EVALUATION,
		SHADER_TYPE_FRAGMENT,
		SHADER_TYPE_GEOMETRY,
		SHADER_TYPE_VERTEX,

		STRING_VENDOR,
		STRING_VERSION,
		STRING_RENDERER,
		STRING_SHADING_LANGUAGE_VERSION,

		TEXTURE_BASE_LEVEL,
		TEXTURE_COMPARE_FUNC,
		TEXTURE_COMPARE_MODE,
		//TEXTURE_DEPTH_STENCIL_MODE,
		TEXTURE_ENV_MODE,
		TEXTURE_LOD_BIAS,
		TEXTURE_MAG_FILTER,
		TEXTURE_MIN_FILTER,
		TEXTURE_MAX_LEVEL,
		TEXTURE_MAX_LOD,
		TEXTURE_MIN_LOD,
		TEXTURE_SWIZZLE_A,
		TEXTURE_SWIZZLE_B,
		TEXTURE_SWIZZLE_G,
		TEXTURE_SWIZZLE_R,
		TEXTURE_WRAP_R,
		TEXTURE_WRAP_S,
		TEXTURE_WRAP_T,

		TYPE_BYTE,
		TYPE_DOUBLE,
		TYPE_FLOAT,
		TYPE_INT,
		TYPE_SHORT,
		TYPE_UNSIGNED_BYTE,
		TYPE_UNSIGNED_INT,
		TYPE_UNSIGNED_SHORT,

		WRAP_MODE_CLAMP,
		WRAP_MODE_REPEAT,
		
		TOTAL_FLAGS,
	};
	
	//----------------------------------------------------------------//
	static _			MapNativeToZL		( u32 value );
	static u32			MapZLToNative		( _ value );
};

//================================================================//
// ZLGfxClearFlags
//================================================================//
struct ZLGfxClearFlags {
	enum _ {
		COLOR_BUFFER_BIT		= 0x01,
		DEPTH_BUFFER_BIT		= 0x02,
		STENCIL_BUFFER_BIT		= 0x04,
	};
};

#define ZGL_INVALID_UNIFORM_ADDR (( u32 )-1 )

#endif
