
set (AUTHOR_NAME "AdHoc")
set (MOAI_VERSION_MINOR FALSE)
set (MOAI_VERSION_REVISION FALSE)


option ( MOAI_APPLE     		"Enable Apple"                  FALSE )
option ( MOAI_SDL       		"Enable SDL"                    FALSE )
option ( MOAI_BOX2D				"Enable Box2D physics"		    TRUE  )
option ( MOAI_CURL      		"Enable Curl"                 	TRUE )
option ( MOAI_LIBCRYPTO 		"Enable Crypto Lib"             TRUE )
option ( MOAI_CRYPTO    		"Enable Moai Crypto classes"    TRUE )
option ( MOAI_EXPAT     		"Enable Expat"                  TRUE )
option ( MOAI_FREETYPE  		"Enable Freetype"               TRUE  )
option ( MOAI_JSON      		"Enable Json"                   TRUE )
option ( MOAI_LUAEXT    		"Enable Lua Extensions"         TRUE )
option ( MOAI_MONGOOSE  		"Enable mongoose"               TRUE )
option ( MOAI_OGG       		"Enable Ogg"                    TRUE )
option ( MOAI_OPENSSL   		"Enable OpenSSL"     			TRUE )
option ( MOAI_SQLITE3   		"Enable Sqlite3"     			TRUE )
option ( MOAI_TINYXML   		"Enable TinyXML" 			    TRUE )
option ( MOAI_SFMT      		"Enable sfmt"    				TRUE )
option ( MOAI_VORBIS    		"Enable vorbis"     			TRUE )
option ( MOAI_UNTZ      		"Enable Untz"     				TRUE )
option ( MOAI_LUAJIT    		"Enable luajit"   			    TRUE  )
option ( MOAI_HTTP_CLIENT  		"Enable HttpClient"          	TRUE )
option ( MOAI_HTTP_SERVER  		"Enable HttpServer"          	FALSE )
option ( MOAI_AUDIO_SAMPLER 	"Enable AudioSampler"       	TRUE )
option ( MOAI_IMAGE_WEBP  		"Enable Webp"          			TRUE )
option ( MOAI_IMAGE_PNG  		"Enable Png"          			TRUE )
option ( MOAI_IMAGE_PVR  		"Enable Pvr"          			TRUE )
option ( MOAI_IMAGE_JPG  		"Enable Jpg"          			TRUE )
