#!/usr/bin/env bash 
INVOKE_DIR=$(pwd)
MOAI_SDK_HOME=$(cd $(dirname "${0}")/../ && pwd)
MOAI_SDK_BIN=$MOAI_SDK_HOME/util/moai
MOAI_CMD=${1}

# if we're missing moai, inform the user that they need to build it first
if ! [ -x "$MOAI_SDK_BIN" ] 
then
    MOAI_BUILD_SCRIPT=""
    case `uname` in
    Darwin*)
        # on OSX, we might have the bin already built
        if [ -x $MOAI_SDK_HOME/bin/osx/moai ] 
        then
            MOAI_SDK_BIN=$MOAI_SDK_HOME/bin/osx/moai
            echo "Warning: pito will use your pre-built MOAI binary at $MOAI_SDK_HOME/bin/osx/moai"
        else
            MOAI_BUILD_SCRIPT="bin/build-osx.sh"
            MOAI_SDK_BIN=$MOAI_SDK_HOME/util/moai
        fi
    ;;
    Linux*)
        MOAI_BUILD_SCRIPT="bin/build-linux.sh"
    ;;
    *)
        echo "Unknown OS"
    ;;
    esac

    echo "bin build script: $MOAI_BUILD_SCRIPT"
    echo "MOAI BIN: $MOAI_SDK_BIN"

    if ! [ -x "$MOAI_SDK_BIN" ]
    then
        if [ -x "$MOAI_BUILD_SCRIPT" ]
        then
            echo "Will use the $MOAI_BUILD_SCRIPT to build $MOAI_SDK_BIN binary for use by pito..."
            $MOAI_BUILD_SCRIPT
            echo "Need to confirm local moai binary was built ..."

            MOAI_SDK_BIN=$MOAI_SDK_HOME/util/moai
            if [ -x $MOAI_SDK_BIN ]
            then
                echo "Continuing pito execution..."
            else
                echo "Something went wrong with building $MOAI_SDK_HOME/util/moai .. exiting!"
                exit 1
            fi
        else
            echo "Could not determine which script to use to build util/moai binary .. aborting"
            exit 1
        fi
    fi
fi

case ${1} in
    wut*)
        echo    "         MOAI SDK location: $MOAI_SDK_HOME"
        echo    "      MOAI binary location: $MOAI_SDK_BIN"
        echo -n "    pito toolbelt location: " && which pito 
        echo
        exit 0
        ;;
esac

# call pito.lua
shift
set $INVOKE_DIR $MOAI_SDK_HOME $MOAI_CMD $@

pushd $MOAI_SDK_HOME/util > /dev/null
$MOAI_SDK_BIN pito.lua $@
popd > /dev/null
