-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:ae3d9c53dbcc3cf94ebaf2a0e6727a8c:1/1$
-- 

return {
	texture = 'squish.png',
	frames = {
			{
				name = "p1.png",
				spriteColorRect = { x = 2, y = 2, width = 250, height = 250 },
				uvRect = { u0 = 0.00390625, v0 = 0.740234, u1 = 0.492188, v1 = 0.984375 },
				spriteSourceSize = { width = 254, height = 254 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "p2.png",
				spriteColorRect = { x = 2, y = 2, width = 250, height = 250 },
				uvRect = { u0 = 0.496094, v0 = 0.501953, u1 = 0.984375, v1 = 0.746094 },
				spriteSourceSize = { width = 254, height = 254 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "p3.png",
				spriteColorRect = { x = 2, y = 2, width = 250, height = 248 },
				uvRect = { u0 = 0.496094, v0 = 0.748047, u1 = 0.984375, v1 = 0.990234 },
				spriteSourceSize = { width = 254, height = 254 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "p4.png",
				spriteColorRect = { x = 2, y = 2, width = 250, height = 250 },
				uvRect = { u0 = 0.00390625, v0 = 0.494141, u1 = 0.492188, v1 = 0.738281 },
				spriteSourceSize = { width = 254, height = 254 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "p5.png",
				spriteColorRect = { x = 0, y = 2, width = 254, height = 250 },
				uvRect = { u0 = 0.503906, v0 = 0.251953, u1 = 0.992188, v1 = 0.5 },
				spriteSourceSize = { width = 254, height = 254 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "p6.png",
				spriteColorRect = { x = 0, y = 2, width = 254, height = 250 },
				uvRect = { u0 = 0.00390625, v0 = 0.248047, u1 = 0.5, v1 = 0.492188 },
				spriteSourceSize = { width = 254, height = 254 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "p7.png",
				spriteColorRect = { x = 0, y = 2, width = 254, height = 250 },
				uvRect = { u0 = 0.503906, v0 = 0.00195312, u1 = 0.992188, v1 = 0.25 },
				spriteSourceSize = { width = 254, height = 254 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "p8.png",
				spriteColorRect = { x = 0, y = 2, width = 254, height = 250 },
				uvRect = { u0 = 0.00390625, v0 = 0.00195312, u1 = 0.5, v1 = 0.246094 },
				spriteSourceSize = { width = 254, height = 254 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}

