language: cpp
compiler:
  - gcc
before_install:
 - sudo apt-get install libboost-regex1.48-dev libboost-system1.48-dev libboost-thread1.48-dev libboost-test1.48-dev libboost-random1.48-dev -y
env:
  global:
    - BOOST_INCLUDES=/usr/include
    - BOOST_LIBS=/usr/lib
script: scons -j 2 && scons test
branches:
  only:
    - master
    - permessage-deflate
    - experimental
    - 0.3.x-cmake
notifications:
  recipients:
    - travis@zaphoyd.com
  email:
    on_success: change
    on_failure: always
